#
# Build and deploy yarn-based project to GitLab Pages
#


variables:
  publish_path: ./public/$CI_COMMIT_BRANCH/
  base_url: /delish/$CI_COMMIT_BRANCH/

stages:
  - build
  - deploy

cache:
  paths:
    - public

build:
  image: node:latest
  stage: build
  script:
    - yarn install --cache-folder .yarn
    - yarn build --base-href ${base_url}
  cache:
    paths:
      - .yarn
  artifacts:
    paths:
      - dist/app

pages:
  image: alpine:latest
  stage: deploy
  script:
    - mkdir -p ${publish_path}
    - cp -aR ./dist/app/* ${publish_path}/
  artifacts:
    paths:
      - public
    expire_in: 2 weeks
  rules:
    - if: ($CI_COMMIT_BRANCH =~ /^wip\//) || ($CI_COMMIT_BRANCH == "main")

