# 
# Build and deploy yarn-based project to GitLab Pages 
#


variables:
  publish_path: ./public/$CI_COMMIT_BRANCH/
  base_url: /delish/$CI_COMMIT_BRANCH/

stages:
  - build
  - deploy

cache:
  paths:
    - .yarn
    - public

build:
  image: node:latest
  stage: build
  script: 
    - yarn install --cache-folder .yarn
    - yarn build --base-href ${base_url}
  artifacts:
    paths:
      - dist/app 

.pages:
  image: alpine:latest
  script:
    - mkdir -p ${publish_path}
    - cp -aR ./dist/app/* ${publish_path}/
  artifacts:
    paths:
      - ${publish_path}

pages-wip:
  extends: .pages
  stage: deploy
  artifacts:
    expire_in: 1 week
  rules:
    - if: ($CI_COMMIT_BRANCH =~ /^wip\//)

pages-main:
  extends: .pages
  stage: deploy
  artifacts:
    expire_in: 10 yrs
  rules:
    - if: ($CI_COMMIT_BRANCH == "main" )
        
